// AUTO-GENERATED by scripts/gen-db-types.ts — do not edit by hand.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      aggregated_results: {
        Row: {
          id: string;
          campaign_id: string;
          scoring_rule_version_id: string;
          engine_version: string;
          payload: Json;
          valid_responses: number;
          computed_at: string;
        };
        Insert: {
          id?: string;
          campaign_id: string;
          scoring_rule_version_id: string;
          engine_version: string;
          payload: Json;
          valid_responses: number;
          computed_at?: string;
        };
        Update: {
          id?: string;
          campaign_id?: string;
          scoring_rule_version_id?: string;
          engine_version?: string;
          payload?: Json;
          valid_responses?: number;
          computed_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "aggregated_results_campaign_id_fkey";
            columns: ["campaign_id"];
            isOneToOne: false;
            referencedRelation: "campaigns";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "aggregated_results_scoring_rule_version_id_fkey";
            columns: ["scoring_rule_version_id"];
            isOneToOne: false;
            referencedRelation: "scoring_rule_versions";
            referencedColumns: ["id"];
          },
        ];
      };
      ai_report_instructions: {
        Row: {
          id: string;
          version_number: number;
          name: string;
          system_prompt: string;
          status: string;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          version_number: number;
          name: string;
          system_prompt: string;
          status?: string;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          version_number?: number;
          name?: string;
          system_prompt?: string;
          status?: string;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [

        ];
      };
      ai_reports: {
        Row: {
          id: string;
          org_id: string;
          campaign_id: string;
          status: string;
          report_level: string;
          generator: string;
          model: string | null;
          instructions_version_id: string | null;
          input_snapshot: Json | null;
          content: Json | null;
          validation_warnings: Json;
          usage: Json | null;
          error: string | null;
          created_by: string | null;
          created_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          org_id: string;
          campaign_id: string;
          status?: string;
          report_level: string;
          generator: string;
          model?: string | null;
          instructions_version_id?: string | null;
          input_snapshot?: Json | null;
          content?: Json | null;
          validation_warnings?: Json;
          usage?: Json | null;
          error?: string | null;
          created_by?: string | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          org_id?: string;
          campaign_id?: string;
          status?: string;
          report_level?: string;
          generator?: string;
          model?: string | null;
          instructions_version_id?: string | null;
          input_snapshot?: Json | null;
          content?: Json | null;
          validation_warnings?: Json;
          usage?: Json | null;
          error?: string | null;
          created_by?: string | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "ai_reports_campaign_id_fkey";
            columns: ["campaign_id"];
            isOneToOne: false;
            referencedRelation: "campaigns";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "ai_reports_instructions_version_id_fkey";
            columns: ["instructions_version_id"];
            isOneToOne: false;
            referencedRelation: "ai_report_instructions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "ai_reports_org_id_fkey";
            columns: ["org_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      app_errors: {
        Row: {
          id: number;
          created_at: string;
          level: string;
          source: string;
          message: string;
          stack: string | null;
          context: Json;
          org_id: string | null;
          resolved: boolean;
        };
        Insert: {
          created_at?: string;
          level?: string;
          source: string;
          message: string;
          stack?: string | null;
          context?: Json;
          org_id?: string | null;
          resolved?: boolean;
        };
        Update: {
          created_at?: string;
          level?: string;
          source?: string;
          message?: string;
          stack?: string | null;
          context?: Json;
          org_id?: string | null;
          resolved?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: "app_errors_org_id_fkey";
            columns: ["org_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      assessment_templates: {
        Row: {
          id: string;
          key: string;
          name: string;
          description: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          name: string;
          description?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          name?: string;
          description?: string | null;
          created_at?: string;
        };
        Relationships: [

        ];
      };
      assessment_versions: {
        Row: {
          id: string;
          template_id: string;
          version_number: number;
          status: string;
          title: string;
          current_label: string;
          desired_label: string;
          change_notes: string | null;
          published_at: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          template_id: string;
          version_number: number;
          status?: string;
          title: string;
          current_label?: string;
          desired_label?: string;
          change_notes?: string | null;
          published_at?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          template_id?: string;
          version_number?: number;
          status?: string;
          title?: string;
          current_label?: string;
          desired_label?: string;
          change_notes?: string | null;
          published_at?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "assessment_versions_template_id_fkey";
            columns: ["template_id"];
            isOneToOne: false;
            referencedRelation: "assessment_templates";
            referencedColumns: ["id"];
          },
        ];
      };
      audit_logs: {
        Row: {
          id: number;
          org_id: string | null;
          actor_user_id: string | null;
          actor_email: string | null;
          scope: string;
          action: string;
          target_type: string | null;
          target_id: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          org_id?: string | null;
          actor_user_id?: string | null;
          actor_email?: string | null;
          scope?: string;
          action: string;
          target_type?: string | null;
          target_id?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          org_id?: string | null;
          actor_user_id?: string | null;
          actor_email?: string | null;
          scope?: string;
          action?: string;
          target_type?: string | null;
          target_id?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "audit_logs_org_id_fkey";
            columns: ["org_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      billing_events: {
        Row: {
          id: string;
          type: string;
          org_id: string | null;
          payload: Json;
          processed_at: string;
          error: string | null;
        };
        Insert: {
          id: string;
          type: string;
          org_id?: string | null;
          payload: Json;
          processed_at?: string;
          error?: string | null;
        };
        Update: {
          id?: string;
          type?: string;
          org_id?: string | null;
          payload?: Json;
          processed_at?: string;
          error?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "billing_events_org_id_fkey";
            columns: ["org_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      campaign_daily_participation: {
        Row: {
          campaign_id: string;
          day: string;
          submissions: number;
        };
        Insert: {
          campaign_id: string;
          day: string;
          submissions?: number;
        };
        Update: {
          campaign_id?: string;
          day?: string;
          submissions?: number;
        };
        Relationships: [
          {
            foreignKeyName: "campaign_daily_participation_campaign_id_fkey";
            columns: ["campaign_id"];
            isOneToOne: false;
            referencedRelation: "campaigns";
            referencedColumns: ["id"];
          },
        ];
      };
      campaign_segment_options: {
        Row: {
          id: string;
          campaign_id: string;
          kind: string;
          label: string;
          sort_order: number;
        };
        Insert: {
          id?: string;
          campaign_id: string;
          kind: string;
          label: string;
          sort_order?: number;
        };
        Update: {
          id?: string;
          campaign_id?: string;
          kind?: string;
          label?: string;
          sort_order?: number;
        };
        Relationships: [
          {
            foreignKeyName: "campaign_segment_options_campaign_id_fkey";
            columns: ["campaign_id"];
            isOneToOne: false;
            referencedRelation: "campaigns";
            referencedColumns: ["id"];
          },
        ];
      };
      campaigns: {
        Row: {
          id: string;
          org_id: string;
          assessment_version_id: string;
          scoring_rule_version_id: string;
          subscription_id: string | null;
          name: string;
          description: string | null;
          status: string;
          privacy_mode: string;
          opens_at: string;
          closes_at: string;
          expected_participants: number | null;
          response_limit: number | null;
          require_access_code: boolean;
          collect_levels: boolean;
          survey_token: string;
          launched_at: string | null;
          closed_at: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          assessment_version_id: string;
          scoring_rule_version_id: string;
          subscription_id?: string | null;
          name: string;
          description?: string | null;
          status?: string;
          privacy_mode?: string;
          opens_at: string;
          closes_at: string;
          expected_participants?: number | null;
          response_limit?: number | null;
          require_access_code?: boolean;
          collect_levels?: boolean;
          survey_token?: string;
          launched_at?: string | null;
          closed_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          assessment_version_id?: string;
          scoring_rule_version_id?: string;
          subscription_id?: string | null;
          name?: string;
          description?: string | null;
          status?: string;
          privacy_mode?: string;
          opens_at?: string;
          closes_at?: string;
          expected_participants?: number | null;
          response_limit?: number | null;
          require_access_code?: boolean;
          collect_levels?: boolean;
          survey_token?: string;
          launched_at?: string | null;
          closed_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "campaigns_assessment_version_id_fkey";
            columns: ["assessment_version_id"];
            isOneToOne: false;
            referencedRelation: "assessment_versions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "campaigns_org_id_fkey";
            columns: ["org_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "campaigns_scoring_rule_version_id_fkey";
            columns: ["scoring_rule_version_id"];
            isOneToOne: false;
            referencedRelation: "scoring_rule_versions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "campaigns_subscription_id_fkey";
            columns: ["subscription_id"];
            isOneToOne: false;
            referencedRelation: "subscriptions";
            referencedColumns: ["id"];
          },
        ];
      };
      contact_inquiries: {
        Row: {
          id: string;
          name: string;
          email: string;
          organization: string | null;
          topic: string | null;
          message: string;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email: string;
          organization?: string | null;
          topic?: string | null;
          message: string;
          status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          organization?: string | null;
          topic?: string | null;
          message?: string;
          status?: string;
          created_at?: string;
        };
        Relationships: [

        ];
      };
      dimensions: {
        Row: {
          id: string;
          version_id: string;
          key: string;
          code: string;
          name: string;
          description: string;
          sort_order: number;
        };
        Insert: {
          id?: string;
          version_id: string;
          key: string;
          code: string;
          name: string;
          description: string;
          sort_order: number;
        };
        Update: {
          id?: string;
          version_id?: string;
          key?: string;
          code?: string;
          name?: string;
          description?: string;
          sort_order?: number;
        };
        Relationships: [
          {
            foreignKeyName: "dimensions_version_id_fkey";
            columns: ["version_id"];
            isOneToOne: false;
            referencedRelation: "assessment_versions";
            referencedColumns: ["id"];
          },
        ];
      };
      generated_reports: {
        Row: {
          id: string;
          org_id: string;
          campaign_id: string;
          ai_report_id: string | null;
          format: string;
          byte_size: number | null;
          sha256: string | null;
          generated_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          campaign_id: string;
          ai_report_id?: string | null;
          format?: string;
          byte_size?: number | null;
          sha256?: string | null;
          generated_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          campaign_id?: string;
          ai_report_id?: string | null;
          format?: string;
          byte_size?: number | null;
          sha256?: string | null;
          generated_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "generated_reports_ai_report_id_fkey";
            columns: ["ai_report_id"];
            isOneToOne: false;
            referencedRelation: "ai_reports";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "generated_reports_campaign_id_fkey";
            columns: ["campaign_id"];
            isOneToOne: false;
            referencedRelation: "campaigns";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "generated_reports_org_id_fkey";
            columns: ["org_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      organization_members: {
        Row: {
          org_id: string;
          user_id: string;
          role_key: string;
          status: string;
          invited_email: string | null;
          invited_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          org_id: string;
          user_id: string;
          role_key: string;
          status?: string;
          invited_email?: string | null;
          invited_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          org_id?: string;
          user_id?: string;
          role_key?: string;
          status?: string;
          invited_email?: string | null;
          invited_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "organization_members_org_id_fkey";
            columns: ["org_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "organization_members_role_key_fkey";
            columns: ["role_key"];
            isOneToOne: false;
            referencedRelation: "roles";
            referencedColumns: ["key"];
          },
        ];
      };
      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          industry: string | null;
          employee_count_range: string | null;
          website: string | null;
          country: string | null;
          region: string | null;
          contact_name: string | null;
          contact_email: string | null;
          contact_title: string | null;
          contact_phone: string | null;
          status: string;
          is_pilot: boolean;
          pilot_notes: string | null;
          is_demo: boolean;
          data_retention_months: number;
          stripe_customer_id: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          industry?: string | null;
          employee_count_range?: string | null;
          website?: string | null;
          country?: string | null;
          region?: string | null;
          contact_name?: string | null;
          contact_email?: string | null;
          contact_title?: string | null;
          contact_phone?: string | null;
          status?: string;
          is_pilot?: boolean;
          pilot_notes?: string | null;
          is_demo?: boolean;
          data_retention_months?: number;
          stripe_customer_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          industry?: string | null;
          employee_count_range?: string | null;
          website?: string | null;
          country?: string | null;
          region?: string | null;
          contact_name?: string | null;
          contact_email?: string | null;
          contact_title?: string | null;
          contact_phone?: string | null;
          status?: string;
          is_pilot?: boolean;
          pilot_notes?: string | null;
          is_demo?: boolean;
          data_retention_months?: number;
          stripe_customer_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [

        ];
      };
      participation_tokens: {
        Row: {
          id: string;
          campaign_id: string;
          token_hash: string;
          kind: string;
          status: string;
          issued_on: string;
        };
        Insert: {
          id?: string;
          campaign_id: string;
          token_hash: string;
          kind: string;
          status?: string;
          issued_on?: string;
        };
        Update: {
          id?: string;
          campaign_id?: string;
          token_hash?: string;
          kind?: string;
          status?: string;
          issued_on?: string;
        };
        Relationships: [
          {
            foreignKeyName: "participation_tokens_campaign_id_fkey";
            columns: ["campaign_id"];
            isOneToOne: false;
            referencedRelation: "campaigns";
            referencedColumns: ["id"];
          },
        ];
      };
      pending_registrations: {
        Row: {
          user_id: string;
          payload: Json;
          created_at: string;
        };
        Insert: {
          user_id: string;
          payload: Json;
          created_at?: string;
        };
        Update: {
          user_id?: string;
          payload?: Json;
          created_at?: string;
        };
        Relationships: [

        ];
      };
      plans: {
        Row: {
          id: string;
          key: string;
          name: string;
          tagline: string | null;
          description: string | null;
          price_cents: number | null;
          currency: string;
          billing_interval: string;
          stripe_price_id: string | null;
          is_public: boolean;
          active: boolean;
          sort_order: number;
          max_campaigns: number | null;
          max_responses_per_campaign: number | null;
          max_admins: number | null;
          access_months: number | null;
          features: Json;
          marketing_bullets: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          name: string;
          tagline?: string | null;
          description?: string | null;
          price_cents?: number | null;
          currency?: string;
          billing_interval: string;
          stripe_price_id?: string | null;
          is_public?: boolean;
          active?: boolean;
          sort_order?: number;
          max_campaigns?: number | null;
          max_responses_per_campaign?: number | null;
          max_admins?: number | null;
          access_months?: number | null;
          features?: Json;
          marketing_bullets?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          name?: string;
          tagline?: string | null;
          description?: string | null;
          price_cents?: number | null;
          currency?: string;
          billing_interval?: string;
          stripe_price_id?: string | null;
          is_public?: boolean;
          active?: boolean;
          sort_order?: number;
          max_campaigns?: number | null;
          max_responses_per_campaign?: number | null;
          max_admins?: number | null;
          access_months?: number | null;
          features?: Json;
          marketing_bullets?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [

        ];
      };
      platform_admins: {
        Row: {
          user_id: string;
          created_at: string;
          created_by: string | null;
        };
        Insert: {
          user_id: string;
          created_at?: string;
          created_by?: string | null;
        };
        Update: {
          user_id?: string;
          created_at?: string;
          created_by?: string | null;
        };
        Relationships: [

        ];
      };
      qualitative_questions: {
        Row: {
          id: string;
          version_id: string;
          key: string;
          prompt: string;
          sort_order: number;
        };
        Insert: {
          id?: string;
          version_id: string;
          key: string;
          prompt: string;
          sort_order: number;
        };
        Update: {
          id?: string;
          version_id?: string;
          key?: string;
          prompt?: string;
          sort_order?: number;
        };
        Relationships: [
          {
            foreignKeyName: "qualitative_questions_version_id_fkey";
            columns: ["version_id"];
            isOneToOne: false;
            referencedRelation: "assessment_versions";
            referencedColumns: ["id"];
          },
        ];
      };
      questions: {
        Row: {
          id: string;
          version_id: string;
          dimension_id: string;
          key: string;
          focus: string;
          prompt: string;
          allow_na: boolean;
          sort_order: number;
        };
        Insert: {
          id?: string;
          version_id: string;
          dimension_id: string;
          key: string;
          focus: string;
          prompt: string;
          allow_na?: boolean;
          sort_order: number;
        };
        Update: {
          id?: string;
          version_id?: string;
          dimension_id?: string;
          key?: string;
          focus?: string;
          prompt?: string;
          allow_na?: boolean;
          sort_order?: number;
        };
        Relationships: [
          {
            foreignKeyName: "questions_dimension_id_fkey";
            columns: ["dimension_id"];
            isOneToOne: false;
            referencedRelation: "dimensions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "questions_version_id_fkey";
            columns: ["version_id"];
            isOneToOne: false;
            referencedRelation: "assessment_versions";
            referencedColumns: ["id"];
          },
        ];
      };
      rate_limits: {
        Row: {
          key: string;
          window_start: string;
          hits: number;
        };
        Insert: {
          key: string;
          window_start: string;
          hits?: number;
        };
        Update: {
          key?: string;
          window_start?: string;
          hits?: number;
        };
        Relationships: [

        ];
      };
      response_comments: {
        Row: {
          id: string;
          campaign_id: string;
          org_id: string;
          qualitative_question_id: string;
          body: string;
          consent_to_quote: boolean;
          is_synthetic: boolean;
        };
        Insert: {
          id?: string;
          campaign_id: string;
          org_id: string;
          qualitative_question_id: string;
          body: string;
          consent_to_quote?: boolean;
          is_synthetic?: boolean;
        };
        Update: {
          id?: string;
          campaign_id?: string;
          org_id?: string;
          qualitative_question_id?: string;
          body?: string;
          consent_to_quote?: boolean;
          is_synthetic?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: "response_comments_campaign_id_fkey";
            columns: ["campaign_id"];
            isOneToOne: false;
            referencedRelation: "campaigns";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "response_comments_org_id_fkey";
            columns: ["org_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "response_comments_qualitative_question_id_fkey";
            columns: ["qualitative_question_id"];
            isOneToOne: false;
            referencedRelation: "qualitative_questions";
            referencedColumns: ["id"];
          },
        ];
      };
      response_items: {
        Row: {
          response_id: string;
          question_id: string;
          current_value: number | null;
          current_na: boolean;
          desired_value: number | null;
          desired_na: boolean;
        };
        Insert: {
          response_id: string;
          question_id: string;
          current_value?: number | null;
          current_na?: boolean;
          desired_value?: number | null;
          desired_na?: boolean;
        };
        Update: {
          response_id?: string;
          question_id?: string;
          current_value?: number | null;
          current_na?: boolean;
          desired_value?: number | null;
          desired_na?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: "response_items_question_id_fkey";
            columns: ["question_id"];
            isOneToOne: false;
            referencedRelation: "questions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "response_items_response_id_fkey";
            columns: ["response_id"];
            isOneToOne: false;
            referencedRelation: "responses";
            referencedColumns: ["id"];
          },
        ];
      };
      responses: {
        Row: {
          id: string;
          campaign_id: string;
          org_id: string;
          assessment_version_id: string;
          department_option_id: string | null;
          location_option_id: string | null;
          level_option_id: string | null;
          tenure_range: string | null;
          is_synthetic: boolean;
        };
        Insert: {
          id?: string;
          campaign_id: string;
          org_id: string;
          assessment_version_id: string;
          department_option_id?: string | null;
          location_option_id?: string | null;
          level_option_id?: string | null;
          tenure_range?: string | null;
          is_synthetic?: boolean;
        };
        Update: {
          id?: string;
          campaign_id?: string;
          org_id?: string;
          assessment_version_id?: string;
          department_option_id?: string | null;
          location_option_id?: string | null;
          level_option_id?: string | null;
          tenure_range?: string | null;
          is_synthetic?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: "responses_assessment_version_id_fkey";
            columns: ["assessment_version_id"];
            isOneToOne: false;
            referencedRelation: "assessment_versions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "responses_campaign_id_fkey";
            columns: ["campaign_id"];
            isOneToOne: false;
            referencedRelation: "campaigns";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "responses_department_option_id_fkey";
            columns: ["department_option_id"];
            isOneToOne: false;
            referencedRelation: "campaign_segment_options";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "responses_level_option_id_fkey";
            columns: ["level_option_id"];
            isOneToOne: false;
            referencedRelation: "campaign_segment_options";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "responses_location_option_id_fkey";
            columns: ["location_option_id"];
            isOneToOne: false;
            referencedRelation: "campaign_segment_options";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "responses_org_id_fkey";
            columns: ["org_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      roles: {
        Row: {
          key: string;
          name: string;
          description: string;
          permissions: string[];
          rank: number;
        };
        Insert: {
          key: string;
          name: string;
          description: string;
          permissions?: string[];
          rank?: number;
        };
        Update: {
          key?: string;
          name?: string;
          description?: string;
          permissions?: string[];
          rank?: number;
        };
        Relationships: [

        ];
      };
      scoring_rule_versions: {
        Row: {
          id: string;
          version_number: number;
          name: string;
          status: string;
          config: Json;
          notes: string | null;
          created_by: string | null;
          created_at: string;
          published_at: string | null;
        };
        Insert: {
          id?: string;
          version_number: number;
          name: string;
          status?: string;
          config: Json;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          published_at?: string | null;
        };
        Update: {
          id?: string;
          version_number?: number;
          name?: string;
          status?: string;
          config?: Json;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          published_at?: string | null;
        };
        Relationships: [

        ];
      };
      subscriptions: {
        Row: {
          id: string;
          org_id: string;
          plan_id: string;
          status: string;
          source: string;
          campaign_credits: number | null;
          limit_overrides: Json;
          started_at: string;
          current_period_end: string | null;
          stripe_subscription_id: string | null;
          stripe_checkout_session_id: string | null;
          notes: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          plan_id: string;
          status: string;
          source: string;
          campaign_credits?: number | null;
          limit_overrides?: Json;
          started_at?: string;
          current_period_end?: string | null;
          stripe_subscription_id?: string | null;
          stripe_checkout_session_id?: string | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          plan_id?: string;
          status?: string;
          source?: string;
          campaign_credits?: number | null;
          limit_overrides?: Json;
          started_at?: string;
          current_period_end?: string | null;
          stripe_subscription_id?: string | null;
          stripe_checkout_session_id?: string | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "subscriptions_org_id_fkey";
            columns: ["org_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "subscriptions_plan_id_fkey";
            columns: ["plan_id"];
            isOneToOne: false;
            referencedRelation: "plans";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      campaign_response_count: { Args: { p_campaign: string }; Returns: number };
      has_org_role: { Args: { p_org: string; p_roles: string[] }; Returns: boolean };
      is_org_member: { Args: { p_org: string }; Returns: boolean };
      is_platform_admin: { Args: Record<PropertyKey, never>; Returns: boolean };
      participation_token_status: { Args: { p_survey_token: string; p_token_hash: string }; Returns: string };
      provision_organization: { Args: { p_user: string; p_email: string; p_payload: Json }; Returns: string };
      rate_limit_hit: { Args: { p_key: string; p_window_seconds: number; p_max: number }; Returns: boolean };
      seed_demo_organization: { Args: Record<PropertyKey, never>; Returns: string };
      submit_survey_response: { Args: { p_survey_token: string; p_token_hash: string; p_profile: Json; p_items: Json; p_comments: Json }; Returns: Json };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};

type PublicSchema = Database["public"];
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"];
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"];
