/**
 * Generates src/lib/database.types.ts (Supabase-compatible `Database` type)
 * by introspecting a PostgreSQL database that has the ROHA migrations applied.
 *
 *   DATABASE_URL=postgres://... npx tsx scripts/gen-db-types.ts
 *
 * Equivalent output can be produced with `supabase gen types typescript`;
 * this script exists so types can be regenerated without Docker.
 */
import { writeFileSync } from "node:fs";
import { Client } from "pg";

const PG_TO_TS: Record<string, string> = {
  uuid: "string",
  text: "string",
  varchar: "string",
  bpchar: "string",
  citext: "string",
  date: "string",
  timestamptz: "string",
  timestamp: "string",
  int2: "number",
  int4: "number",
  int8: "number",
  float4: "number",
  float8: "number",
  numeric: "number",
  bool: "boolean",
  jsonb: "Json",
  json: "Json",
};

function tsType(udt: string): string {
  if (udt.startsWith("_")) return `${tsType(udt.slice(1))}[]`;
  return PG_TO_TS[udt] ?? "unknown";
}

async function main() {
  const client = new Client({ connectionString: process.env.DATABASE_URL });
  await client.connect();

  const { rows: cols } = await client.query(`
    select c.table_name, c.column_name, c.udt_name, c.is_nullable, c.column_default,
           c.is_identity, c.is_generated
    from information_schema.columns c
    join information_schema.tables t on t.table_name = c.table_name and t.table_schema = c.table_schema
    where c.table_schema = 'public' and t.table_type = 'BASE TABLE'
    order by c.table_name, c.ordinal_position`);

  const { rows: fks } = await client.query(`
    select con.conname as name, rel.relname as table_name,
           array(select att.attname from unnest(con.conkey) k join pg_attribute att on att.attrelid = con.conrelid and att.attnum = k)::text[] as columns,
           frel.relname as ref_table,
           array(select att.attname from unnest(con.confkey) k join pg_attribute att on att.attrelid = con.confrelid and att.attnum = k)::text[] as ref_columns,
           exists (
             select 1 from pg_index i
             where i.indrelid = con.conrelid and i.indisunique
               and (select array_agg(x order by x) from unnest(i.indkey::int2[]) x) = (select array_agg(x order by x) from unnest(con.conkey) x)
           ) as one_to_one
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace n on n.oid = rel.relnamespace
    join pg_class frel on frel.oid = con.confrelid
    join pg_namespace fn on fn.oid = frel.relnamespace
    where con.contype = 'f' and n.nspname = 'public' and fn.nspname = 'public'
    order by rel.relname, con.conname`);

  const { rows: fns } = await client.query(`
    select p.proname as name,
           coalesce(p.proargnames, array[]::text[])::text[] as arg_names,
           array(select format_type(t, null) from unnest(p.proargtypes) t) as arg_types,
           format_type(p.prorettype, null) as return_type
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public' and p.prokind = 'f'
      and format_type(p.prorettype, null) <> 'trigger'
      and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')
    order by p.proname`);

  await client.end();

  const tables = new Map<string, typeof cols>();
  for (const c of cols) {
    if (!tables.has(c.table_name)) tables.set(c.table_name, []);
    tables.get(c.table_name)!.push(c);
  }

  const fmtType: Record<string, string> = {
    uuid: "string", text: "string", jsonb: "Json", boolean: "boolean", integer: "number",
    "timestamp with time zone": "string", "text[]": "string[]", void: "undefined",
  };

  let out = `// AUTO-GENERATED by scripts/gen-db-types.ts — do not edit by hand.\n\n`;
  out += `export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];\n\n`;
  out += `export type Database = {\n  public: {\n    Tables: {\n`;
  for (const [table, columns] of tables) {
    const row = columns.map((c) => `          ${c.column_name}: ${tsType(c.udt_name)}${c.is_nullable === "YES" ? " | null" : ""};`).join("\n");
    const insert = columns
      .filter((c) => c.is_generated !== "ALWAYS" && !(c.is_identity === "YES"))
      .map((c) => {
        const optional = c.is_nullable === "YES" || c.column_default !== null;
        return `          ${c.column_name}${optional ? "?" : ""}: ${tsType(c.udt_name)}${c.is_nullable === "YES" ? " | null" : ""};`;
      })
      .join("\n");
    const update = columns
      .filter((c) => c.is_generated !== "ALWAYS" && !(c.is_identity === "YES"))
      .map((c) => `          ${c.column_name}?: ${tsType(c.udt_name)}${c.is_nullable === "YES" ? " | null" : ""};`)
      .join("\n");
    const rels = fks
      .filter((f) => f.table_name === table)
      .map(
        (f) => `          {
            foreignKeyName: "${f.name}";
            columns: [${f.columns.map((c: string) => `"${c}"`).join(", ")}];
            isOneToOne: ${f.one_to_one};
            referencedRelation: "${f.ref_table}";
            referencedColumns: [${f.ref_columns.map((c: string) => `"${c}"`).join(", ")}];
          },`,
      )
      .join("\n");
    out += `      ${table}: {\n        Row: {\n${row}\n        };\n        Insert: {\n${insert}\n        };\n        Update: {\n${update}\n        };\n        Relationships: [\n${rels}\n        ];\n      };\n`;
  }
  out += `    };\n    Views: { [_ in never]: never };\n    Functions: {\n`;
  for (const f of fns) {
    const args = (f.arg_types as string[])
      .map((t, i) => `${(f.arg_names as string[])[i] ?? `arg${i}`}: ${fmtType[t] ?? "unknown"}`)
      .join("; ");
    out += `      ${f.name}: { Args: ${args ? `{ ${args} }` : "Record<PropertyKey, never>"}; Returns: ${fmtType[f.return_type] ?? "unknown"} };\n`;
  }
  out += `    };\n    Enums: { [_ in never]: never };\n    CompositeTypes: { [_ in never]: never };\n  };\n};\n\n`;
  out += `type PublicSchema = Database["public"];\n`;
  out += `export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"];\n`;
  out += `export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"];\n`;
  out += `export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"];\n`;

  const target = process.argv[2] ?? "src/lib/database.types.ts";
  writeFileSync(target, out);
  console.log(`Wrote ${target} (${tables.size} tables, ${fns.length} functions)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
